# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  windows-build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64
    - name: Build
      run: dotnet build --no-restore -c Release --self-contained
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

  macos-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: TEMPORARY use correct Xcode version, see https://github.com/actions/runner-images/issues/12751
      run: sudo xcode-select -s "/Applications/Xcode_16.4.app"
    - name: Install MAUI Workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore -r ios-arm64
    - name: Build
      run: dotnet build --no-restore -c Release --self-contained
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
